# Generated by Django 4.2.11 on 2025-09-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_sortir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortirorganizersettings',
            name='api_url_production',
            field=models.URLField(default='https://api.apras.fr', help_text='URL de l\'API APRAS en production', verbose_name='URL API Production'),
        ),
        migrations.AddField(
            model_name='sortirorganizersettings',
            name='api_url_test',
            field=models.URLField(default='https://test-api.apras.fr', help_text='URL de l\'API APRAS en test', verbose_name='URL API Test'),
        ),
    ]