# Generated by Django 4.2.23 on 2025-09-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0288_invoice_transmission'),
        ('pretix_sortir', '0002_add_api_url_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sortirusage',
            new_name='pretix_sort_event_i_9db569_idx',
            old_name='pretix_sort_event_i_5b5c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='sortirusage',
            new_name='pretix_sort_order_i_3b0bde_idx',
            old_name='pretix_sort_order_i_e5c0c9_idx',
        ),
        migrations.RemoveField(
            model_name='sortiritemconfig',
            name='sortir_price',
        ),
        migrations.AlterField(
            model_name='sortiritemconfig',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortir_item_configs', to='pretixbase.event'),
        ),
        migrations.AlterField(
            model_name='sortiritemconfig',
            name='requires_sortir',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sortirorganizersettings',
            name='api_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sortirorganizersettings',
            name='prefill_attendee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sortirorganizersettings',
            name='salt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sortirusage',
            name='apras_request_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sortirusage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.event'),
        ),
        migrations.AlterField(
            model_name='sortirusage',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.item'),
        ),
        migrations.AlterField(
            model_name='sortirusage',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.order'),
        ),
        migrations.AlterField(
            model_name='sortirusage',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortirusage',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.itemvariation'),
        ),
        migrations.AddIndex(
            model_name='sortirusage',
            index=models.Index(fields=['event', 'status'], name='pretix_sort_event_i_a67f40_idx'),
        ),
    ]
